force-app/main/default/objects/Case/fields/Alleged_Issue__c.field-meta.xml
<CustomField>
    <fullName>Alleged_Issue__c</fullName>
    <label>Alleged Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alignment</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Bluetooth</fullName>
            </value>
            <value>
                <fullName>Burr/rough edges</fullName>
            </value>
            <value>
                <fullName>Button/Touchscreen/Knob</fullName>
            </value>
            <value>
                <fullName>Coating</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Deformed</fullName>
            </value>
            <value>
                <fullName>Dirty</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Error Codes</fullName>
            </value>
            <value>
                <fullName>Fan</fullName>
            </value>
            <value>
                <fullName>Firmware</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Heat</fullName>
            </value>
            <value>
                <fullName>Incorrectly assembled parts</fullName>
            </value>
            <value>
                <fullName>Injection molding process</fullName>
            </value>
            <value>
                <fullName>Leaking</fullName>
            </value>
            <value>
                <fullName>Measurement</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Noise</fullName>
            </value>
            <value>
                <fullName>Odor</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Shrinkage marks visible</fullName>
            </value>
            <value>
                <fullName>Third-party</fullName>
            </value>
            <value>
                <fullName>Stability</fullName>
            </value>
            <value>
                <fullName>Poor welding</fullName>
            </value>
            <value>
                <fullName>Uneven side gaps</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <label>Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Fry basket does not close properly</fullName>
            </value>
            <value>
                <fullName>Fry basket inconvenient to assemble/disassemble</fullName>
            </value>
            <value>
                <fullName>Gap/offset too large</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>App crashes</fullName>
            </value>
            <value>
                <fullName>Push notifications delay</fullName>
            </value>
            <value>
                <fullName>Registration/login issues</fullName>
            </value>
            <value>
                <fullName>Bluetooth Pairing Issues</fullName>
            </value>
            <value>
                <fullName>Bluetooth Scanning Failure</fullName>
            </value>
            <value>
                <fullName>Auto-press button issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
            <value>
                <fullName>Bubbling</fullName>
            </value>
            <value>
                <fullName>Peeling</fullName>
            </value>
            <value>
                <fullName>Rust</fullName>
            </value>
            <value>
                <fullName>Scratches</fullName>
            </value>
            <value>
                <fullName>Button/Touchscreen/Knob Damaged</fullName>
            </value>
            <value>
                <fullName>Door latch/hinge broken</fullName>
            </value>
            <value>
                <fullName>Fry bucket decorative panel cracked</fullName>
            </value>
            <value>
                <fullName>Fry bucket front panel falling off</fullName>
            </value>
            <value>
                <fullName>Fry bucket rubber plug falling off</fullName>
            </value>
            <value>
                <fullName>Handle dent</fullName>
            </value>
            <value>
                <fullName>Housing dent</fullName>
            </value>
            <value>
                <fullName>Screen dent</fullName>
            </value>
            <value>
                <fullName>Top cover lifting up</fullName>
            </value>
            <value>
                <fullName>Fry basket deformation</fullName>
            </value>
            <value>
                <fullName>Plug Deformation</fullName>
            </value>
            <value>
                <fullName>Housing deformation</fullName>
            </value>
            <value>
                <fullName>Air bubbles</fullName>
            </value>
            <value>
                <fullName>Basket/outer basket body</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Main_Category__c.field-meta.xml
<CustomField>
    <fullName>Main_Category__c</fullName>
    <label>Main Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Appearance Issues</fullName>
            </value>
            <value>
                <fullName>Hardware Issues</fullName>
            </value>
            <value>
                <fullName>High Priority Issues</fullName>
            </value>
            <value>
                <fullName>Production Issues</fullName>
            </value>
            <value>
                <fullName>Software Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SubDetail__c.field-meta.xml
<CustomField>
    <fullName>SubDetail__c</fullName>
    <label>SubDetail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basket coating</fullName>
            </value>
            <value>
                <fullName>Fryer coating</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Inner basket</fullName>
            </value>
            <value>
                <fullName>Basket</fullName>
            </value>
            <value>
                <fullName>Outer basket</fullName>
            </value>
            <value>
                <fullName>Crisper Plate</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Frame</fullName>
            </value>
            <value>
                <fullName>Screen/Panel</fullName>
            </value>
            <value>
                <fullName>Fryer basket pops out</fullName>
            </value>
            <value>
                <fullName>Coating bubbling</fullName>
            </value>
            <value>
                <fullName>Tray coating bubbling</fullName>
            </value>
            <value>
                <fullName>Back panel</fullName>
            </value>
            <value>
                <fullName>Crumb tray</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Button/Touchscreen/Knob</fullName>
            </value>
            <value>
                <fullName>Coating</fullName>
            </value>
            <value>
                <fullName>Glass door</fullName>
            </value>
            <value>
                <fullName>Rubber feet</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Wire rack</fullName>
            </value>
            <value>
                <fullName>Door</fullName>
            </value>
            <value>
                <fullName>Part</fullName>
            </value>
            <value>
                <fullName>Plastic part</fullName>
            </value>
            <value>
                <fullName>Panel</fullName>
            </value>
            <value>
                <fullName>Screen</fullName>
            </value>
            <value>
                <fullName>Basket detaching during use</fullName>
            </value>
            <value>
                <fullName>Short Circuit/Trip</fullName>
            </value>
            <value>
                <fullName>Stops working with a bang</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/Case_Picklist_Mapping__c.object-meta.xml
<CustomObject>
    <label>Case Picklist Mapping</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Case Picklist Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Picklist Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Alleged_Issue__c.field-meta.xml
<CustomField>
    <fullName>Alleged_Issue__c</fullName>
    <label>Alleged Issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <label>Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Main_Category__c.field-meta.xml
<CustomField>
    <fullName>Main_Category__c</fullName>
    <label>Main Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Sub_Detail__c.field-meta.xml
<CustomField>
    <fullName>Sub_Detail__c</fullName>
    <label>Sub Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Warranty_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warranty Mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cosori</fullName>
    </customValue>
    <customValue>
        <fullName>Etekcity</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit</fullName>
    </customValue>
    <customValue>
        <fullName>PawSync</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit;Etekcity</fullName>
        <isActive>false</isActive>
        <label>Levoit;Etekcity</label>
    </customValue>
    <customValue>
        <fullName>Etekcity;Cosori</fullName>
        <isActive>false</isActive>
        <label>Etekcity;Cosori</label>
    </customValue>
    <customValue>
        <fullName>Levoit;Levoit</fullName>
        <isActive>false</isActive>
        <label>Levoit;Levoit</label>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Air Fryer</fullName>
    </customValue>
    <customValue>
        <fullName>Air Fryer Toaster Oven</fullName>
    </customValue>
    <customValue>
        <fullName>Air Mattress</fullName>
    </customValue>
    <customValue>
        <fullName>Air Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Air Purifier</fullName>
    </customValue>
    <customValue>
        <fullName>Air Purifier Filter</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Pets Feeders</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>Body Fat Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Body Weight Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Lantern</fullName>
    </customValue>
    <customValue>
        <fullName>Coffe Grinder</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Maker</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Warmer</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Kettle</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Toothbrush</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Food Dehydrator</fullName>
    </customValue>
    <customValue>
        <fullName>Foot Massager</fullName>
    </customValue>
    <customValue>
        <fullName>Gooseneck Kettle</fullName>
    </customValue>
    <customValue>
        <fullName>Humidifier</fullName>
    </customValue>
    <customValue>
        <fullName>Hygrothermograph</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor Grill</fullName>
    </customValue>
    <customValue>
        <fullName>Kitchen Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Luggage Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Massager</fullName>
    </customValue>
    <customValue>
        <fullName>Multimeter</fullName>
    </customValue>
    <customValue>
        <fullName>Nutrition Scales</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Remote Outlet</fullName>
    </customValue>
    <customValue>
        <fullName>Pressure Cooker</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WarrantyPicklistController.cls
public class WarrantyPicklistController {
    
    @Auraenabled
    public Static case getCaseDetails(Id recordId){
        
        try{
            Case caseRecord = [Select Id,Main_Category__c, Alleged_Issue__c, Detail__c, SubDetail__c from case where Id =: recordId];
            
            return caseRecord;
        }
        catch(Exception e){
            system.debug(e.getmessage());
        }
        return null;
    } 
    
    @AuraEnabled
    public static wrapper returnPicklistValues(Id recordId, String mainCategory, String allegedIssue, String detail, String subDetail ){
        Case caseRecord= [Select Brand__c, Product_Category__c from case where Id=: recordId];
        
        if(caseRecord.Brand__c == '' || caseRecord.Brand__c == null || caseRecord.Product_Category__c == ''  || caseRecord.Product_Category__c == null){
            return null;
        }
        else{
            List<String> mainCatgeoryValues = new List<String>();
            List<String> allegedIssueValues = new List<String>();
            List<String> detailValues = new List<String>();
            List<String> subDetailValues = new List<String>();
            
            for(Case_Picklist_Mapping__c mapValue : [Select Main_Category__c from Case_Picklist_Mapping__c where Warranty_Mapping__c = true AND Brand__c = :caseRecord.Brand__c AND(Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Main_Category__c ]){
                if(!mainCatgeoryValues.contains(mapValue.Main_Category__c)){
                    mainCatgeoryValues.add(mapValue.Main_Category__c);
                }
            }
            
            if(mainCategory != null && mainCategory != ''){
                for(Case_Picklist_Mapping__c mapValue : [Select Alleged_Issue__c from Case_Picklist_Mapping__c where Warranty_Mapping__c = true AND Brand__c = :caseRecord.Brand__c AND Main_Category__c =:mainCategory  AND(Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Alleged_Issue__c ]){
                    if(!allegedIssueValues.contains(mapValue.Alleged_Issue__c)){
                        allegedIssueValues.add(mapValue.Alleged_Issue__c);
                    }
                }
                
                if(allegedIssue != null && allegedIssue != ''){
                    for(Case_Picklist_Mapping__c mapValue : [Select Detail__c from Case_Picklist_Mapping__c where Warranty_Mapping__c = true AND Brand__c = :caseRecord.Brand__c AND Main_Category__c =:mainCategory AND Alleged_Issue__c =: allegedIssue   AND(Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Detail__c ]){
                        if(!detailValues.contains(mapValue.Detail__c)){
                            detailValues.add(mapValue.Detail__c);
                        }
                    }
                    
                    if(detail != null && detail != ''){
                        for(Case_Picklist_Mapping__c mapValue : [Select Sub_Detail__c from Case_Picklist_Mapping__c where Warranty_Mapping__c = true AND Brand__c = :caseRecord.Brand__c AND Main_Category__c =:mainCategory AND Alleged_Issue__c =: allegedIssue AND Detail__c =:detail   AND(Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Sub_Detail__c ]){
                            if(!subDetailValues.contains(mapValue.Sub_Detail__c)){
                                subDetailValues.add(mapValue.Sub_Detail__c);
                            }
                        }
                    }
                }
            }
            
            Wrapper wrap = new Wrapper();
            wrap.mainCategoryValueSet = mainCatgeoryValues;
            wrap.allegedIssueValueSet = allegedIssueValues;
            wrap.detailValueSet = detailValues;
            wrap.subDetailValueSet = subDetailValues;
            
            return wrap;
            
        }
        
        
    }
    
    
    public Class wrapper{
        @auraEnabled public List<String> mainCategoryValueSet;
        @auraEnabled public List<String> allegedIssueValueSet ;
        @auraEnabled public List<String> detailValueSet ;
        @auraEnabled public List<String> subDetailValueSet;
        
        public wrapper(){
            //typeValueSet = new List<String>();
            mainCategoryValueSet = new List<String>();
            allegedIssueValueSet = new List<String>();
            detailValueSet = new List<String>();
            subDetailValueSet = new List<String>(); 
        }
    }
    
    @AuraEnabled
    public static String saveCaseRecord(Id recordId, String mainCategory, String allegedIssue, String detail, String subDetail ){
        
        try{
            Case caseRecord = [Select Id,Main_Category__c, Alleged_Issue__c, Detail__c, SubDetail__c from case where Id =: recordId];
            
            caseRecord.Main_Category__c =  caseRecord.Main_Category__c != mainCategory ? (mainCategory == ''? null : mainCategory) : caseRecord.Main_Category__c;
            caseRecord.Alleged_Issue__c =  caseRecord.Alleged_Issue__c != allegedIssue ? (allegedIssue == '' ? null : allegedIssue) : caseRecord.Alleged_Issue__c;
            caseRecord.Detail__c =  caseRecord.Detail__c != detail ? (detail == '' ? null: detail) : caseRecord.Detail__c;
            caseRecord.SubDetail__c =  caseRecord.SubDetail__c != subDetail ? (subDetail == ''? null: subDetail) : caseRecord.SubDetail__c;
            
            update caseRecord;
        }
        catch(Exception e){
            return e.getMessage();
        }
        return 'Updated';
    }
    
}