force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Feedback_Detail__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Detail__c</fullName>
    <label>Feedback Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Difficulty filling out registration</fullName>
            </value>
            <value>
                <fullName>Difficulty finding batch #</fullName>
            </value>
            <value>
                <fullName>Difficulty finding model #</fullName>
            </value>
            <value>
                <fullName>Insufficient Support</fullName>
            </value>
            <value>
                <fullName>QR code issues</fullName>
            </value>
            <value>
                <fullName>Short warranty period</fullName>
            </value>
            <value>
                <fullName>Slow Response</fullName>
            </value>
            <value>
                <fullName>Unable to Contact</fullName>
            </value>
            <value>
                <fullName>Unsatisfactory customer service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Feedback_Reason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Reason__c</fullName>
    <label>Feedback Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>After-Sales Service</fullName>
            </value>
            <value>
                <fullName>Customer Review</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>General Appearance</fullName>
            </value>
            <value>
                <fullName>General Feedback</fullName>
            </value>
            <value>
                <fullName>Literature</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Marketing/UX/Sales</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Physical Sensitivities</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Size</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Demo Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Feedback_SubReason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_SubReason__c</fullName>
    <label>Feedback SubReason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ability to turn off some bulbs</fullName>
            </value>
            <value>
                <fullName>Accessories hard to use</fullName>
            </value>
            <value>
                <fullName>Add backlight feature</fullName>
            </value>
            <value>
                <fullName>Add calibration function</fullName>
            </value>
            <value>
                <fullName>Add Chinese option in app</fullName>
            </value>
            <value>
                <fullName>Add decimal places to &quot;g&quot; unit</fullName>
            </value>
            <value>
                <fullName>Add Desktop Shortcut</fullName>
            </value>
            <value>
                <fullName>Additional language</fullName>
            </value>
            <value>
                <fullName>Add magnetic feature</fullName>
            </value>
            <value>
                <fullName>Add Pregnancy Mode</fullName>
            </value>
            <value>
                <fullName>Add Product Warning Information to Listing</fullName>
            </value>
            <value>
                <fullName>Add switch</fullName>
            </value>
            <value>
                <fullName>Air hose too short</fullName>
            </value>
            <value>
                <fullName>Air Output Cold</fullName>
            </value>
            <value>
                <fullName>Alert Sound Too Loud</fullName>
            </value>
            <value>
                <fullName>Alert Sound Too Quiet</fullName>
            </value>
            <value>
                <fullName>Allergic to Gel</fullName>
            </value>
            <value>
                <fullName>All settings feel the same</fullName>
            </value>
            <value>
                <fullName>App cannot find product</fullName>
            </value>
            <value>
                <fullName>App features limited</fullName>
            </value>
            <value>
                <fullName>App forces logout</fullName>
            </value>
            <value>
                <fullName>App Surveys Users Too Early</fullName>
            </value>
            <value>
                <fullName>Arm strap size not suitable</fullName>
            </value>
            <value>
                <fullName>Auto-off occurs too quickly</fullName>
            </value>
            <value>
                <fullName>Auto-shutoff time needs adjustment</fullName>
            </value>
            <value>
                <fullName>Bag too short for easy covering</fullName>
            </value>
            <value>
                <fullName>Basket hard to insert</fullName>
            </value>
            <value>
                <fullName>Basket size issue</fullName>
            </value>
            <value>
                <fullName>Beep sound too loud</fullName>
            </value>
            <value>
                <fullName>Beep sound too soft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Feedback_Type__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Type__c</fullName>
    <label>Feedback Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Experience</fullName>
            </value>
            <value>
                <fullName>User Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/Case_Picklist_Mapping__c.object-meta.xml
<CustomObject>
    <label>Case Picklist Mapping</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Case Picklist Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Picklist Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Feedback_Detail__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Detail__c</fullName>
    <label>Feedback Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Feedback_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Feedback Mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Feedback_Reason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Reason__c</fullName>
    <label>Feedback Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Feedback_SubReason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_SubReason__c</fullName>
    <label>Feedback SubReason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Picklist_Mapping__c/fields/Feedback_Type__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Type__c</fullName>
    <label>Feedback Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cosori</fullName>
    </customValue>
    <customValue>
        <fullName>Etekcity</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit</fullName>
    </customValue>
    <customValue>
        <fullName>PawSync</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit;Etekcity</fullName>
        <isActive>false</isActive>
        <label>Levoit;Etekcity</label>
    </customValue>
    <customValue>
        <fullName>Etekcity;Cosori</fullName>
        <isActive>false</isActive>
        <label>Etekcity;Cosori</label>
    </customValue>
    <customValue>
        <fullName>Levoit;Levoit</fullName>
        <isActive>false</isActive>
        <label>Levoit;Levoit</label>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Air Fryer</fullName>
    </customValue>
    <customValue>
        <fullName>Air Fryer Toaster Oven</fullName>
    </customValue>
    <customValue>
        <fullName>Air Mattress</fullName>
    </customValue>
    <customValue>
        <fullName>Air Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Air Purifier</fullName>
    </customValue>
    <customValue>
        <fullName>Air Purifier Filter</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Pets Feeders</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>Body Fat Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Body Weight Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Lantern</fullName>
    </customValue>
    <customValue>
        <fullName>Coffe Grinder</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Maker</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Warmer</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Kettle</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Toothbrush</fullName>
    </customValue>
    <customValue>
        <fullName>Fitness Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Food Dehydrator</fullName>
    </customValue>
    <customValue>
        <fullName>Foot Massager</fullName>
    </customValue>
    <customValue>
        <fullName>Gooseneck Kettle</fullName>
    </customValue>
    <customValue>
        <fullName>Humidifier</fullName>
    </customValue>
    <customValue>
        <fullName>Hygrothermograph</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor Grill</fullName>
    </customValue>
    <customValue>
        <fullName>Kitchen Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Luggage Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Massager</fullName>
    </customValue>
    <customValue>
        <fullName>Multimeter</fullName>
    </customValue>
    <customValue>
        <fullName>Nutrition Scales</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Remote Outlet</fullName>
    </customValue>
    <customValue>
        <fullName>Pressure Cooker</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CasePicklistController.cls
public class CasePicklistController {
    
    @AuraEnabled(cacheable = true)
    public Static case getCaseDetails(Id recordId){
        
        Case caseRecord = [Select Id,
                           Brand__c,
                           Feedback_Type__c,
                           Feedback_Reason__c,
                           Feedback_SubReason__c,
                           Feedback_Detail__c 
                           FROM case 
                           WHERE Id =: recordId];
        
        return caseRecord;
    }
    
    
    
    @AuraEnabled
    public static Wrapper returnPicklistValues(Id recordId, String feedbackType, String reason, String subReason, String detail ){
        Case caseRecord= [Select Brand__c, Product_Category__c from case where Id=: recordId];
        String Brand = caseRecord.Brand__c;  
        
        system.debug(caseRecord);
        if(Brand == '' || Brand == null){
            return null;
        }
        else {
            
            
            List<String> typeValues = new List<String>();
            List<String> reasonValues = new List<String>();
            List<String> subReasonValues = new List<String>();
            List<String> detailValues = new List<String>();
            
            for(Case_Picklist_Mapping__c mapValue : [SELECT Feedback_Type__c 
                                                     FROM Case_Picklist_Mapping__c 
                                                     WHERE Feedback_Mapping__c = TRUE 
                                                     AND Brand__c = :Brand 
                                                     AND (Product_Category__c = :caseRecord.Product_Category__c 
                                                          OR Product_Category__c LIKE 'All%') order by Feedback_Type__c
                                                    ]) {
                                                        if(!typeValues.contains(mapValue.Feedback_Type__c))
                                                            typeValues.add(mapValue.Feedback_Type__c);
                                                    }           
            if(feedbackType != null ){
                for(Case_Picklist_Mapping__c mapValue : [Select  Feedback_Reason__c from Case_Picklist_Mapping__c  WHERE Feedback_Mapping__c = TRUE and Brand__c =: Brand and Feedback_Type__c =: feedbackType AND (Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%')  order by Feedback_Reason__c]){
                    if(!reasonValues.contains(mapValue.Feedback_Reason__c))
                        reasonValues.add(mapValue.Feedback_Reason__c);
                }
                
                if(reason != null){
                    for(Case_Picklist_Mapping__c mapValue : [Select  Feedback_SubReason__c from Case_Picklist_Mapping__c  WHERE Feedback_Mapping__c = TRUE and Brand__c =: Brand and Feedback_Type__c =: feedbackType and  Feedback_Reason__c =: reason AND (Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Feedback_SubReason__c]){
                        if(!subReasonValues.contains(mapValue.Feedback_SubReason__c))
                            subReasonValues.add(mapValue.Feedback_SubReason__c);
                    }
                    
                    if(subreason != null){
                        for( Case_Picklist_Mapping__c mapValue : [Select  Feedback_Detail__c from Case_Picklist_Mapping__c  WHERE Feedback_Mapping__c = TRUE and Brand__c =: Brand and Feedback_Type__c =: feedbackType and  Feedback_Reason__c =: reason AND Feedback_SubReason__c =:subReason AND (Product_Category__c = :caseRecord.Product_Category__c OR Product_Category__c LIKE 'All%') order by Feedback_Detail__c ]){
                            if(!detailValues.contains(mapValue.Feedback_Detail__c))
                                detailValues.add(mapValue.Feedback_Detail__c);
                        }
                    }
                }
            }
            
            Wrapper wrap = new Wrapper();
            wrap.typeValueSet = typeValues;
            wrap.reasonValueSet = reasonValues;
            wrap.subreasonValueSet = subReasonValues;
            wrap.detailValueSet = detailValues;
            
            return wrap;
        }
        
        
    }
    
    @AuraEnabled
    public static String saveCaseRecord(Id caseId, String feedbackType, String reason, String subReason, String detail ){
        
        try{
            
            Case caseRecord = [Select Id,
                               Brand__c,
                               Feedback_Type__c,
                               Feedback_Reason__c,
                               Feedback_SubReason__c,
                               Feedback_Detail__c 
                               FROM case 
                               WHERE Id =: caseId];
            
            caseRecord.Feedback_Type__c =  caseRecord.Feedback_Type__c != feedbackType ? (feedbackType == ''? null : feedbackType) : caseRecord.Feedback_Type__c;
            caseRecord.Feedback_Reason__c =  caseRecord.Feedback_Reason__c != reason ? (reason == '' ? null : reason) : caseRecord.Feedback_Reason__c;
            caseRecord.Feedback_SubReason__c =  caseRecord.Feedback_SubReason__c != subReason ? (subReason == '' ? null: subReason) : caseRecord.Feedback_SubReason__c;
            caseRecord.Feedback_Detail__c =  caseRecord.Feedback_Detail__c != detail ? (detail == ''? null: detail) : caseRecord.Feedback_Detail__c;
            
            update caseRecord;
        }
        catch(Exception e){
            return e.getMessage();
        }
        
        return 'Updated';
        
    }
    
    
    public Class wrapper{
        @auraEnabled public List<String> typeValueSet;
        @auraEnabled public List<String> reasonValueSet ;
        @auraEnabled public List<String> subreasonValueSet ;
        @auraEnabled public List<String> detailValueSet;
        
        public wrapper(){
            typeValueSet = new List<String>();
            reasonValueSet = new List<String>();
            subreasonValueSet = new List<String>();
            detailValueSet = new List<String>();
            
        }
    }
}