force-app/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Austrilia</fullName>
            </value>
            <value>
                <fullName>Eastern Asia</fullName>
            </value>
            <value>
                <fullName>European Union</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Mainland</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Tailand</fullName>
            </value>
            <value>
                <fullName>The United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>United Kingdom of Great Britain and Northern Ireland</fullName>
            </value>
            <value>
                <fullName>United States of America,Canada</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cosori</fullName>
    </customValue>
    <customValue>
        <fullName>Etekcity</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit</fullName>
    </customValue>
    <customValue>
        <fullName>PawSync</fullName>
    </customValue>
    <customValue>
        <fullName>Levoit;Etekcity</fullName>
        <isActive>false</isActive>
        <label>Levoit;Etekcity</label>
    </customValue>
    <customValue>
        <fullName>Etekcity;Cosori</fullName>
        <isActive>false</isActive>
        <label>Etekcity;Cosori</label>
    </customValue>
    <customValue>
        <fullName>Levoit;Levoit</fullName>
        <isActive>false</isActive>
        <label>Levoit;Levoit</label>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AgentWorkHandlerTest.cls
@IsTest
public class AgentWorkHandlerTest {
    @TestSetup
    static void setupTestData() {
        List<Case> caseList = new List<Case>();
        for (Integer i = 0; i < 5; i++) {
            caseList.add(new Case(
                Subject = 'Test Case ' + i,
                Status = 'New',
                Origin = 'Web',
                Brand__c='Levoit',
                Country__c='United States Of America',
                OwnerId=UserInfo.getUserId(),
                Priority='Medium',
                Description='this record is for test class purpose'  
            ));
        }
        insert caseList;
        Set<Id> testCaseID = new Set<Id>();
        for (Case c : caseList) {
            testCaseID.add(c.Id);
        }
        
        
        
    }
    @IsTest
    static void testMainEntry(){
        ServiceChannel channel = [Select Id from ServiceChannel limit 1];
        Group gr = [Select Id,name, QueueRoutingConfigId from Group where QueueRoutingConfigId != null limit 1];
      	
        AgentWorkHandler.testCoverage();
    }
}